apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: yoomanyoo/flask-todo-app:v5   # ← Change this!
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:SuperSecret123@db:5432/postgres"